version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    container_name: "nginx"
    volumes:
      - "/root/nginx/html:/usr/share/nginx/html"
      - "/root/nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "/root/nginx/logs:/var/log/nginx"
      - "/root/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
      - "/etc/localtime:/etc/localtime:ro"
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    container_name: "mysql"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: "redis"
    volumes:
      - "/root/docker/redis/redis.conf:/etc/redis/redis.conf"
      - "/root/docker/redis/data:/data"
      - "/etc/localtime:/etc/localtime:ro"
    command: redis-server /etc/redis/redis.conf
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: "rabbitmq"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"

