spring:
  application:
    name: consumer-rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8612
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true

