server:
  port: 8650

master-ip: 172.17.0.1
oauth-server: http://${master-ip}:9120
spring:
  main:
    #    允许自己的实例覆盖系统默认的实例
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${master-ip}:3306/seckill?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    username: root
    password: 123456
  redis:
    host: ${master-ip}
    port: 6379
    password: 123456
    timeout: 20000
    database: 0
  rabbitmq:
    host: ${master-ip}
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    #    发送心跳时间间隔 默认30
    lease-renewal-interval-in-seconds: 10
    #    服务端收到最后一次心跳之后等待的时间上限 超过则剔除（客户端告诉服务端按照此规则）
    lease-expiration-duration-in-seconds: 22
swagger:
  base-package: zcs.${spring.application.name}.controller
  title: ${spring.application.name}接口文档

security:
  oauth2:
    resource:
      id: ${spring.application.name}
      #      资源服务器三种验证令牌方法
      #       一、在ResourceServerConfig中本地配置
      #      二、从认证服务器获取用户信息 解析出token
      #      user-info-uri: ${oauth-server}/oauth2_token/current
      #      prefer-token-info: false
      #       三、远程获取公钥 解析token
      jwt:
        key-uri: ${oauth-server}/oauth/token_key