server:
  port: 8650

zk:
  address: 106.14.45.78:2181

spring:
  main:
    #    允许自己的实例覆盖系统默认的实例
    allow-bean-definition-overriding: true
swagger:
  base-package: zcs.${spring.application.name}.controller
  title: ${spring.application.name}接口文档

#security:
#  oauth2:
#    resource:
#      id: ${spring.application.name}
#      #      资源服务器三种验证令牌方法
#      #       一、在ResourceServerConfig中本地配置
#      #      二、从认证服务器获取用户信息 解析出token
#      #      user-info-uri: ${oauth-server}/oauth2_token/current
#      #      prefer-token-info: false
#      #       三、远程获取公钥 解析token
#      jwt:
#        key-uri: ${oauth-server}/oauth/token_key